version: '3.8'

services:
  cd-server:
    build:
      context: ./ci_cd-server
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ci_cd_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tester:
    build:
      context: ./tests
    depends_on:
      - cd-server

volumes:
  postgres-data:
